### ISSUE TITLE
Possible feature to save raw-frame from camera?

### ISSUE THREAD

**Issue by beniroquai** [ShawnBaker/RPiCameraViewer#1]
Hey! I am looking for a solution to stream the Raspicam images to an android device. I haven't looked into your code yet, but would you thank that it's possible to press the button on the phone and save a 5MP image on the SD card for example? This would really help! :-) thank you very much. Great work!!!

**Comment by ShawnBaker** [comment]
I've added the ability to take a local snapshot on the Android device. Unfortunately, taking snapshots on the Raspberry Pi is not supported and probably won't be. That would require a program running on the Pi that would respond to snapshot requests. This program doesn't really communicate with the Pi, it just reads the stream that is being sent out.

**Comment by beniroquai** [comment]
Cool! Thank you for the feature. So you say, I would need to write a programm on raspberry side to interrupt the stream to capture a frame, save it, send it to the phone and restart the stream? 
I'm trying to implement it in a Python script, but I have no idea how to trigger the stop-signal via an android command. I was thinking about a php-post or something, but this would not have any influecne on the running script, right?

Thanks!

**Comment by ShawnBaker** [comment]
I would have the Python script on the Pi listen for commands on a socket. It would then run whatever processes are necessary to either stream or take snapshots. As long as it keeps handles to those processes, it can stop them whenever it needs to. The Android program would then send commands through a socket of its own. Take a look at **scripts/player.py** for an example of how to run and manage processes.

Have you looked at [Picamera](https://www.raspberrypi.org/documentation/usage/camera/python/README.md)?

**Comment by ShawnBaker** [comment]
You might also want to look at my new project, CurlingTV. It has a Python server that provides H.264 streams as well as still images. I'm using it to provide a private TV system for our curling club, but it's really a general purpose CCTV server and client.

**Comment by beniroquai** [comment]
Hey! Thank you very much for your advice! I've looked into your code and found some lines which could help, but I'm not a Python programmer, thus it's becomming really hard to understand how it is working - at least for me ;)..
So far my setup (too bad I'm not a canuck anymore and therefore don't see much Curling here in europe..;) ):
I have built a small lensless-microscope which has an LCD, an LED and a Motor. LCD+LED represent a small projector which creates light-patterns, Motor is the Z-Stage. The android phone does the processing (if you like, the setup can be seen here: https://beniroquai.wordpress.com/) and communication with the RaspiCam and initialize the acquisition process.

Whats working so far: Livestreaming the camera-view to the phone and display it. With you'r app it works flawelessly. I've also managed to implement a second http-socket which sends commands for the LED/Motor-section. So I can controle the microscope

What should work: Press a button "Acquisition" which then trigger the process. Take eg. 9 photos with different LCD-patterns and then download the images to the phones sd. Everything works, but when I try to "pause" the python image stream the python script breaks. 
What you did: 
`camera.start_recording(output, format='h264', bitrate=BPS)`
and at a time (I actually don't know what is representing the trigger signal) you do this:
`self.camera.capture(stream, 'jpeg', use_video_port=True)`

So I somehow need to figure out, how I can start streaming the camera to the android and then get full-resolution (best would be RAW-resolution) images out of the ring-buffer. 
I've posted my code on [github ](https://github.com/beniroquai/Holoscope-Raspberry/blob/master/PythonCameraScanScript_GLOBAL_SIMULTANIOUS3.py)as the first part of the upcoming "release" in the near/far future. Maybe you've some suggestion you could give - I'm definitly not a programmer though. 

Anyway thank you very much for your hard work and making it OpenSource! :+1: 

Best regards!
