### ISSUE TITLE
Width and Height Ratio in Display can not be changed and some more suggestions

### ISSUE THREAD

**Issue by sgon00** [ShawnBaker/RPiCameraViewer#2]
First, thank you very much for your app. It has much lower latency than the app called _"RaspberryPi Camera Viewer"_. That app has a latency of 1 to 2 seconds. This app (your app) has a latency of about 0.3 seconds and it's really close to real time, sometimes, I even can't find the latency. I tried `mplayer -fps 200 -demuxer h264es ffmpeg://tcp://<ip>:5001` in my linux laptop, it looks real time to me and a little better than this app. I am trying to build a real time monitoring camera. So real time is really important to me. And your app saves my life. Thanks a lot.

Some suggestions:

1, I am using 640x640 witdth*height on the pi camera which has a fisheye lens. This ratio gives me the best visual field/angle. But this app seems using the fixed ratio, so my video output is stretched. This is not what I expected. Hopefully, you can provide the ratio parameter in the edit view in the future. I tried to modify the width and height, but it doesn't help. The ratio can not be changed. It looks like it's always 16:10.

2, As what I talked in the beginning, can the app reduce the latency even more? I know it's currently very perfect compared to other apps. But it's not as good as my mplayer in linux laptop. I know my laptop has better CPU and hardware than my mobile. If this can not be improved, it's ok. You have done a very excellent job already.

3, the capture icon will disappear after a few seconds the camera launched. I can still capture photos by pressing that position. But I don't really know if my capture is successful or not. So maybe it's better to have a success popup notification.

4, The app does not have the permission of _"prevent device from sleeping"_. Thus my mobile screen is always turned off automatically. This is not what I expected. Hopefully, this permission can be added in the future. 

OK, that's all. Thank you very much for your time and app. It's the best app which has the lowest latency I can find so far. Thanks! ^_^

**Comment by ShawnBaker** [comment]
I apologize for the very slow reply. I live on a farm and we lost our Internet connection in July. We just got it back last week.

As for your suggestions:

1. I fixed the code to maintain the video's aspect ratio.

2. I tried to get things to be as fast as possible, but there are a couple of possibilities. Basically the program just reads from a TCP/IP socket and feeds the bytes into a decoder. There's a newer way to feed buffers to the decoder, but I want the program to work on older versions of Android, so I don't use it. You could try playing with the read size (TCPIP_BUFFER_SIZE), it might be faster if the size was smaller.

3. The snapshot button now displays a message saying that the image has been saved. It also now asks the user for storage permission on Android 6+. All of the controls should fade out after a few seconds and tapping the screen should bring them all back. I've never had the snapshot button disappear on its own.

4. The video activity now prevents the device from sleeping.

Thank you for the excellent message, now I have a question for you. What did you use for a fisheye lens. I've tried several things with wide angle lenses, but I can't get anything to work.
