### ISSUE TITLE
Take pictures button doesn't seem to work

### ISSUE THREAD

**Issue by etatus** [ShawnBaker/RPiCameraViewer#3]
When I try to take a picture while watching the video streaming, the button seems to do nothing. My device is a Galaxy S7 - Android 6.0.1.

Thank you in advance and congratulations for this amazing app!

**Comment by ShawnBaker** [comment]
I apologize for the slow reply. I live on a farm and we lost our Internet connection in July. We just got it back last week.

They changed the way that permissions work in Android 6, so now the program has to prompt the user for write permission to the pictures folder. I've added that code to the snapshot button handler. Thanks for pointing this out.
