### ISSUE TITLE
Open sourcing library.aar

### ISSUE THREAD

**Issue by ajhool** [ShawnBaker/RPiCameraViewer#5]
Hey, this app is incredibly useful, great work!

If I'm not mistaken, the RPiCameraViewer/ca.frozen.library/library-release.aar is generated with closed source and it contains a few critical classes. My goal is to process incoming frames before they reach the ZoomPanTextureView, but I believe this functionality is currently locked away.

 Would it be possible to make some/all of this code available?

**Comment by ShawnBaker** [comment]
The source is available as one of my other github projects. It's at https://github.com/ShawnBaker/Library.
