### ISSUE TITLE
More documentation for the app?

### ISSUE THREAD

**Issue by Sidney2408** [ShawnBaker/RPiCameraViewer#6]
Hi Shawn, thank you for making this app.

One issue I am facing is the lack of documentation to understand your code. Though my main query is this:
How do you receive and process the H264 video stream from the Raspberry pi, and which java files contain the functionality for it? 
What kind of libraries are used?
What does player.py do?

**Comment by ShawnBaker** [comment]
The video activity (VideoActivity.java) creates the video fragment (VideoFragment.java), which is where all the real work is done. The video fragment uses one of the reader classes (usually TcpIpReader) and the main loop starts with:

    while (!isInterrupted())
    {
        int len = reader.read(buffer);

The TcpIpReader class is given an IP address and a port and it opens a socket on that address/port. The main loop continuously reads the stream from the socket, breaks the stream up into NAL units, and feeds the NAL units into the decoder, which then feeds the decoded frames directly into the surface it has been configured with.

The only library being used is ca.frozen.library, which is another one of my open source projects. It's at:

    https://github.com/ShawnBaker/Library

player.py was intended to run on an RPi connected directly to a TV where a remote control would be used to select which stream (channel) you want to view. I didn’t finish or test it.
