### ISSUE TITLE
Can't discover/ connect cam with Android 9.0 device

### ISSUE THREAD

**Issue by d-wolf** [ShawnBaker/RPiCameraViewer#8]
At first, thank you for your effort creating that great App! Unfortunately i can't discover/ connect my camera with my Nokia 7.1 running Android 9.0. On my Samsung Galaxy A3 running Android 8.1 it works perfectly.

**Comment by weirdgyn** [comment]
Have you checked log files?

**Comment by d-wolf** [comment]
It works now and i have no idea why.
